### PR TITLE
Added first work in progress to retrieve the data from the CRTM server.

### PR DESCRIPTION
**Pull request by danibaena**

### CODE REVIEW

**Comment by jsenin** [comment]
Hi @danibaena I just review your pull request, looks fine but all code in on the root dir, so it's needed move the code for reordering an be able to mix with other code.
I suggest this structure : 
```
- READE.md

- src\
--app.js
--bin
--controllers
--lib -> piston would be here
--models
--package.json
--public
--routes
--views

- spec\
-- lib
```

this skel was build using jasmine and express generators. Only controllers dir it's mine.
what do you think ?

**Comment by danibaena** [comment]
Hi, yes, it's fine for me. That's why I wanted to make the PR in the first place, so we can think a better way to organize the different pieces of the project on a more standarized way. The structure you posted looks good to me ;)

**Comment by danibaena** [comment]
Hi Jorge. I think I have ready the DataSource module finished, need more testing though. I might give you a hand with the other stuff if you publish it. Best regards.

**Comment by jsenin** [comment]
Sorry for this long delay ;)

**Pull request merged**
